# Generated by Django 4.2.20 on 2025-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_id', models.CharField(max_length=100)),
                ('scale_id', models.CharField(default='1', max_length=10)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('party_type', models.CharField(default='CLIENT', max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('print_date', models.DateField()),
                ('challan_no', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('qty', models.CharField(blank=True, max_length=100)),
                ('load_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_weight_date', models.DateTimeField()),
                ('unload_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unload_weight_date', models.CharField(blank=True, max_length=100)),
                ('deduct', models.CharField(default='0', max_length=10)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
